// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVgC_Rl_yFrBBqZH2xQyxl5xluhncayRU',
    appId: '1:157182298181:web:xxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '157182298181',
    projectId: 'eco-watch-c7a55',
    authDomain: 'eco-watch-c7a55.firebaseapp.com',
    storageBucket: 'eco-watch-c7a55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcJYlwEaSU7Ae8PhfY6Pt2CWP82ik4kys',
    appId: '1:157182298181:android:ee12eedfef287b9b4bbb2c',
    messagingSenderId: '157182298181',
    projectId: 'eco-watch-c7a55',
    storageBucket: 'eco-watch-c7a55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJYlwEaSU7Ae8PhfY6Pt2CWP82ik4kys',
    appId: '1:157182298181:ios:xxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '157182298181',
    projectId: 'eco-watch-c7a55',
    storageBucket: 'eco-watch-c7a55.firebasestorage.app',
    iosBundleId: 'com.example.daiict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcJYlwEaSU7Ae8PhfY6Pt2CWP82ik4kys',
    appId: '1:157182298181:ios:xxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '157182298181',
    projectId: 'eco-watch-c7a55',
    storageBucket: 'eco-watch-c7a55.firebasestorage.app',
    iosBundleId: 'com.example.daiict',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVgC_Rl_yFrBBqZH2xQyxl5xluhncayRU',
    appId: '1:157182298181:web:xxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '157182298181',
    projectId: 'eco-watch-c7a55',
    authDomain: 'eco-watch-c7a55.firebasestorage.app',
    storageBucket: 'eco-watch-c7a55.firebasestorage.app',
  );
}